---
title: "Influential factors of days spent at the shelter"
author: "Hanfan Chen 2703334C, Zhaohao Li 2611602L, Zhenhao Qiao 2612824Q, Chao Wang 2518608W, RachaelWatson 2195719W"
output:
  pdf_document:
    number_sections: yes
fig_caption: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(eval = T, echo = FALSE, comment = NA, message = FALSE, warning = FALSE)
```

# Introduction

```{r library}
library(ggplot2)
library(GGally)
library(tidyverse)
library(kableExtra)
```

# Exploratory Data Analysis
```{r read the data}
data10 <- read.csv("dataset10.csv")
head(data10)
```

```{r}
for (i in 1:6) {
  cat("Column", i,":")
  print(levels(as.factor(data10[,i])))
  cat("\n")
}
```

```{r}
zero_data <- subset(data10, time_at_shelter == 0)
nrow(zero_data)
```

```{r hist of y, fig.cap = "\\label{fig:y_hist} The histogram of day time at shelter", fig.width = 10, fig.align = "center", fig.pos = "H"}
ggplot(data10, mapping = aes(x = time_at_shelter)) + 
  geom_histogram(bins = 25)
```

```{r pair plots, fig.cap = "\\label{fig:pairs} Pair plots of the variables", fig.width = 10, fig.align = "center", fig.pos = "H"}
ggpairs(data10,
upper=list(continuous=wrap("points", alpha=0.4)),
lower="blank", axisLabels="none")
```

```{r bar plot 1, fig.cap = "\\label{fig:bar1} Option 1: Bar plot of outcome type vs time at shelter", fig.width = 10, fig.align = "center", fig.pos = "H"}
ggplot(data10, aes(x=outcome_type, y=time_at_shelter, colour=outcome_type, fill=outcome_type)) +
  geom_col() +
  labs(x="Outcome Type", y="Time at Shelter")
```

```{r bar plot 2, fig.cap = "\\label{fig:bar2} Option 2: Bar plot of outcome type vs count", fig.width = 10, fig.align = "center", fig.pos = "H"}
count <- data10 %>% 
  group_by(outcome_type) %>% 
  summarise(count = n())

ggplot(count, aes(x=outcome_type, y=count, colour=outcome_type, fill=outcome_type))+
  geom_col() +
  labs(x="Outcome Type", y="Count")
```

```{r bar plot 3, fig.cap = "\\label{fig:bar3} Option 3: Bar plot of outcome type vs max time at shelter", fig.width = 10, fig.align = "center", fig.pos = "H"}
max <- data10 %>% 
  select(outcome_type, time_at_shelter) %>% 
  group_by(outcome_type) %>% 
  summarise(max = max(time_at_shelter))

ggplot(max, aes(x=outcome_type, y=max, colour=outcome_type, fill=outcome_type))+
  geom_col() +
  labs(x="Outcome Type", y="Max Time at Shelter")
```

This is just so you can see that there's no overlap between the months and years.
```{r}
data10 %>% 
  filter(year==2016) %>% 
  select(month) %>% 
  unique()

data10 %>% 
  filter(year==2017) %>% 
  select(month) %>% 
  unique()
```

# Formal Data Analysis

# Conclusions {#sec:Conc}










































